### ISSUE TITLE
Errors don't appear on console when file is not found

### ISSUE THREAD

**Issue by raniesantos** [wiledal/gulp-include#59]
I was testing your plugin when I found this weird behavior.
My gulp task looks like this. (uglify commented-out on purpose)

~~~js
// gulpfile.js

gulp.task("scripts", function() {
	return gulp
		.src("./_source/scripts/site.js")
		.pipe(sourcemaps.init())
		.pipe(include()).on("error", console.log)
		// .pipe(uglify())
		.pipe(sourcemaps.write())
		.pipe(gulp.dest("./assets/js"));
});
~~~

the src file looks like this

~~~js
// site.js input/gulp.src

//=include functions.js
//=include ../../vendor/package/js/doesntexist.js
~~~

It DOES NOT LOG ERRORS, it simply continues and the output file ends up looking like this
The include/require statement ends up in the output file.

~~~js
// site.js output/gulp.dest

console.log("functions.js was included");

//=include ../../vendor/package/js/doesntexist.js
~~~

**Comment by ranietots32** [comment]
I have browsed previous issues and I have found [this issue](https://github.com/wiledal/gulp-include/issues/37) that *you have closed without giving a proper solution*.

I want to make it clear that `.pipe(include()).on("error", console.log)` DOES NOT WORK. The expected behavior is it should terminate the operation and not create an output file at all, and log errors into the console.
