### ISSUE TITLE
Conditional include based on environment variables [Feature Req]

### ISSUE THREAD

**Issue by shadow1runner** [wiledal/gulp-include#64]
Because I'm in the dilemma right now I'm wondering if other users might have the same use case as I do:

I need to do include code files conditionally (due to different build targets with different instruction set), therefore it would be nice if I could define an environment variable which is passed via e.g. `include( { buildVersion: 1.0})` and I can _require_ or _include_ the files based on a condition.

Or does somebody of you guys have a convenient solution for this?
Currently I'm looking at [gulp-regex-replace](https://www.npmjs.com/package/gulp-regex-replace) to do this job

Thanks

**Comment by wiledal** [comment]
I feel this is a bit of an edge case which could be solved in how you set up your build scripts.
In this case I would probably target different files, so that you can control the includes.

`main-vXX.js` or similar for the different build targets...
Possibly you can use `yargs` or similar to add some more modularity to your gulp script.

```js
var gulp = require("gulp"),
    watch = require("gulp-watch"),
    include = require("gulp-include"),
    argv = require("yargs").argv;

gulp.task("build", function() {
  if (!argv.version) return console.log("No version set, please use --version");

  gulp.src("assets-src/js/main-v"+argv.version+".js")
    .pipe(include())
    .pipe(gulp.dest("assets/js"));
});
```

You'd then call `gulp build --version 1.0` which will build `assets-src/js/main-v1.0.js`.

**Comment by shadow1runner** [comment]
I agree that that's really an edge case and thus shouldn't be part of gulp-include.
But the feature I was originally thinking of was more just to get my use case clear:
```
#ifdef WINDOWS
//=include <windows.h>
#else
//=include <nix.h>
#endif
```
